# Generated by Django 5.2.4 on 2024-06-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0001_initial"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="assistant_teachers",
            field=models.ManyToManyField(
                related_name="assistant_teachers", to="teachers.teacher"
            ),
        ),
    ]
